version: '3.8'

services:
  mysql:
    image: mariadb:10.6.1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 33006:3306
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql -schemas=tmpdb -user=root -password=root -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - mysql         
  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080